### ISSUE TITLE
BLBL报错（csrf校验失败）

### ISSUE THREAD

**Issue by sunny7010** [KD-happy/KDCheckin#17]
【哔哩哔哩 日志】
好名字7010 开始签到...
{'code': 1011040, 'message': '今日已签到过,无法重复签到', 'ttl': 1, 'data': None}
直播签到: 重复签到
{'code': 'invalid_argument', 'msg': 'clockin clockin is duplicate', 'meta': {'argument': 'clockin'}}
漫画签到: 重复签到
{'code': 0, 'message': '0', 'ttl': 1, 'data': {'login': True, 'watch': True, 'coins': 0, 'share': False, 'email': True, 'tel': True, 'safe_question': True, 'identify_card': True}}
今日经验: 10
观看视频: 今日已完成
{"code":-111,"message":"csrf 校验失败","ttl":1}
分享任务: csrf 校验失败
394906559: 投币失败，csrf 校验失败
392119002: 投币失败，csrf 校验失败
562532255: 投币失败，csrf 校验失败
598257134: 投币失败，csrf 校验失败
908896350: 投币失败，csrf 校验失败
735802313: 投币失败，csrf 校验失败
投币任务: 5/0
{'code': 0, 'message': '0', 'ttl': 1, 'data': {'login': True, 'watch': True, 'coins': 0, 'share': False, 'email': True, 'tel': True, 'safe_question': True, 'identify_card': True}}
今日经验: 10
{"code":-111,"message":"csrf 校验失败","ttl":1}
当前硬币和银币数: 144/686
好名字7010: 异常 Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/KDCheckin/BLBL.py", line 459, in SignIn
    if self.sendBag(one, one.get('gift_num')):
  File "/workspace/KDCheckin/BLBL.py", line 251, in sendBag
    res = requests.get(url=f'https://api.bilibili.com/x/space/acc/info?mid={self.mID}', headers=headers).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 47 (char 46)

【哔哩哔哩】
账号信息: 好名字7010
直播签到: 重复签到
漫画签到: 重复签到
观看视频: 今日已完成
分享任务: csrf 校验失败
投币任务: 5/0
今日经验: 10
银瓜子兑硬币: csrf 校验失败
当前硬币和银币数: 144/686
签到存在异常, 请自行查看签到日志

gocq 推送未配置, 推送失败
pushplus 推送完成
push+ 推送未配置, 推送失败
ding 推送未配置, 推送失败
ding 推送失败, 查看一下配置文件
qywx 推送未配置, 推送失败

**Comment by sunny7010** [comment]
cookie填错了，抱歉打扰了
