### ISSUE TITLE
天气预报运行报错

### ISSUE THREAD

**Issue by RookieApe** [KD-happy/KDCheckin#22]
Traceback (most recent call last):
  File "/ql/data/scripts/KD-happy_KDCheckin/Weather.py", line 84, in <module>
    send('天气预报', sio.getvalue())
  File "/ql/data/scripts/KD-happy_KDCheckin/KDconfig.py", line 161, in send
    while(message[-1] == '\n'):
IndexError: string index out of range

**Comment by KD-happy** [comment]
给的错误信息太少了，其次我这里没有问题

**Comment by RookieApe** [comment]
手动加了print,找到原因
【天气预报 日志】

{'message': 'CityId101240108不在返回之内,加QQ群：608222884，反馈问题。', 'status': 403}
