### ISSUE TITLE
> 啥问题

### ISSUE THREAD

**Issue by xqhyx** [KD-happy/KDCheckin#26]
> 啥问题
> ![Uploading Screenshot_2023-09-12-16-01-41-082_org.mozilla.firefox.jpg…]()
> 

你这图片都没上传好吧，看不见。还有我这里测试是正常签到的，没有错误

_Originally posted by @KD-happy in https://github.com/KD-happy/KDCheckin/issues/25#issuecomment-1715217027_

**Comment by xqhyx** [comment]
![Uploading Screenshot_2023-09-12-16-13-28-979_org.mozilla.firefox.jpg…]()

**Comment by xqhyx** [comment]
![Screenshot_2023-09-12-16-13-28-979_org mozilla firefox](https://github.com/KD-happy/KDCheckin/assets/144187099/2f5ea43e-fa1f-4c81-9a05-3bd232c8422e)

**Comment by xqhyx** [comment]
抱歉抱歉，刚刚注册，还不是很熟练

**Comment by xqhyx** [comment]
然后执行上面的那个命令也报错.请问需要提供日志吗

**Comment by KD-happy** [comment]
https://github.com/KD-happy/KDCheckin/issues/10

你可以看一下这个issue，这是那次版本更新后，有人提示的错误，如果还不懂，那就没办法了，，，

**Comment by xqhyx** [comment]
成功捣鼓好了.我看到可以直接运行py以为是需要的的参数直接填到py就OK了，我还寻思为啥没注释..

**Comment by xqhyx** [comment]
其次葫芦侠参数超过三个会稳定报错.不知道是不是玄学问题，两个就没事

Traceback (most recent call last):
  File "/ql/data/scripts/KD-happy_KDCheckin/HLX.py", line 118, in <module>
    config = getYmlConfig('Cookie.yml')
  File "/ql/data/scripts/KD-happy_KDCheckin/KDconfig.py", line 21, in getYmlConfig
    config = yaml.load(file_data, Loader=yaml.FullLoader)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 121, column 5:
        send: 1
        ^
expected <block end>, but found '<block sequence start>'
  in "<unicode string>", line 131, column 7:
          - user:
          ^

**Comment by KD-happy** [comment]
配置文件错误吧，缩进格式要严格符合要求的。
