### ISSUE TITLE
52签到大家都正常吗？

### ISSUE THREAD

**Issue by geelinsir** [KD-happy/KDCheckin#27]
异常 Traceback (most recent call last):
File "D:\scripts\KDCheckin\W2PJ.py", line 71, in SignIn
self.task()
File "D:\scripts\KDCheckin\W2PJ.py", line 29, in task
p1 = re.findall('\|\/(.*=)\|', res.text)[0]
IndexError: list index out of range

**Comment by crux92** [comment]
一样，前几天开始出现异常
